version: '2'
# SERVICES
services:
# MYSQL
  mysql:
    image: mysql:5.7
    volumes:
      - /docker/app_data/:/var/lib/mysql/
    ports:
      - 3366:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: laravel
       MYSQL_USER: laravel
       MYSQL_PASSWORD: laravel
  # Composer
  composer:
    depends_on:
      - php
    image: composer:latest
    volumes_from:
      - php:rw
    links:
      - php
  # PHP
  php:
    depends_on:
      - mysql
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 8181:8080
    volumes:
      - /docker/app/:/var/www/app/:rw
      # php configs
      - /docker/docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
  # NGINX
  nginx:
    depends_on:
      - mysql
      - php
    image: nginx:latest
    ports:
      - 80:80
    volumes_from:
      - php:rw
    volumes:
      - /docker/app_logs/:/var/log/nginx/app/
      # nginx configs
      - /docker/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php